apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: fraud-detection
data:
  DB_TYPE: "postgresql"
  PG_HOST: "postgres-service"
  PG_PORT: "{{ .Values.postgres.service.port }}"
  PG_DBNAME: "{{ .Values.postgres.database }}"
  PG_USER: "{{ .Values.postgres.username }}"
