apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  labels:
    app: fraud-detection
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.postgres.password }}"
  PG_PASSWORD: "{{ .Values.postgres.password }}"
  GEMINI_API_KEY: "CHANGE_ME"
  GROQ_API_KEY: "CHANGE_ME"
