apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection
spec:
  type: {{ .Values.webapp.service.type }}
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: {{ .Values.webapp.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.webapp.service.nodePort }}
